---
- name: Server Monitor
  hosts: db
  gather_facts: false
  become: true
  pre_tasks:
    - name: update and upgrade
      apt:
        upgrade: dist
        update_cache: true
  roles:
    - server_monitor
