- name: download process_exporter
  get_url:
    url: 'https://github.com/ncabatoff/process-exporter/releases/download/v{{ process_exporter_version }}/process-exporter-{{ process_exporter_version }}.linux-amd64.tar.gz'
    dest: '/tmp/process-exporter-{{ process_exporter_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: unarchive process_exporter
  unarchive:
    src: '/tmp/process-exporter-{{ process_exporter_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/tmp'

- name: copy process_exporter binary
  copy:
    src: '/tmp/process-exporter-{{ process_exporter_version }}.linux-amd64/process-exporter'
    dest: '/usr/local/bin/'
    remote_src: true
    owner: root
    group: root
    mode: 755

- name: create process_exporter systemd unit
  copy:
    src: process_exporter.service
    dest: /etc/systemd/system/process_exporter.service
    owner: root
    group: root
    mode: '600'

- name: Creates Process Exporter directory
  file:
    path: '/etc/process-exporter'
    state: directory
    owner: root
    group: root
    recurse: true
    mode: 0755
  changed_when: false

- name: copy config file
  copy:
    src: process_exporter_config.yml
    dest: /etc/process-exporter/config.yml
    owner: root
    group: root
    mode: '600'
  changed_when: false

- name: start process_exporter service
  systemd:
    name: process_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
