---
- name: Install MySQL
  apt:
    name: mysql-server
    state: latest

- name: copy config file
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart mysql
